name: release

on:
  push:
    tags:
      - "v*"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary: critica-linux-amd64
          - goos: linux
            goarch: arm64
            binary: critica-linux-arm64
          - goos: darwin
            goarch: amd64
            binary: critica-darwin-amd64
          - goos: darwin
            goarch: arm64
            binary: critica-darwin-arm64
          - goos: windows
            goarch: amd64
            binary: critica-windows-amd64.exe
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.23.2"
          cache: true
          cache-dependency-path: go.sum

      - run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          go build -trimpath -ldflags "-s -w" -o "dist/${{ matrix.binary }}"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary }}
          path: dist/${{ matrix.binary }}

  release:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/**/critica-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
